name: 'Deploy to AWS CloudFormation'

on: 
  push:
    branches: [ master ]
  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Configure AWS Credentials to have access to cloudFormation service
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: us-east-1

      - name: Deploy to AWS CloudFormation using Github Action
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: tekloon-test-stack
          template: cloudFormationTemplate.yaml
          no-fail-on-empty-changeset: "1"
